name: connectedx
description: ""
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  window_manager: ^0.3.8
  wolt_modal_sheet: ^0.5.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.0
  flutter_html: ^3.0.0-beta.2
  permission_handler: ^8.3.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: "^0.13.1"
  launcher_name: "^1.0.2"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/images/icon.png"
    - "assets/images/icon_ios.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_ios.png"

launcher_name:
  default: "ConnecTEDx"